# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Art Du Vin Winebar
email: info@artduvinwinebar.com
description: > # this means to ignore newlines until "baseurl:"
  Art Du Vin is a European-style wine bar on Retro Row in Long Beach known for its cozy atmosphere and unique wine, beer, meat and cheese. We are the “Cheers” of wine bars in Long Beach. Open 5pm to midnight, 7 days a week.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artduvinwinebar.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
