url: http://www.artduvinwinebar.com
baseurl: 

# Site settings
title: Art Du Vin Winebar
email: info@artduvinwinebar.com
description: "Art Du Vin is a European-style wine bar on Retro Row in Long Beach known for its cozy atmosphere and unique wine, beer, meat and cheese. We are the “Cheers” of wine bars in Long Beach. Open 5pm to midnight, 7 days a week."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "950201"
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Stephanie Blakeslee
  pic: 1
  position: Owner, Sommelier
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


- name: Byron Brno
  pic: 2
  position: Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


- name: Shauna
  pic: 3
  position: Bartender
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/stephanie_adv
  - title: facebook
    url: https://www.facebook.com/ArtDuVin/
  - title: instagram
    url: https://instagram.com/artduvin

# Postal address (add as many lines as necessary)
address:
  - line: 2027 E. 4th Street
  - line: Long Beach, CA 90814

# Build settings
markdown: kramdown
permalink: pretty